name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build_image:
    runs-on: ubuntu-22.04
    steps:

      - uses: actions/checkout@v4

      - name: Refresh repositories and upgrade packages
        run: |
          sudo apt update && sudo apt upgrade -y

      - name: Install required software
        run: sudo apt install -y qemu-utils grub-pc

      - name: Linux Release
        run: |
          ver=$(git describe --tags --exact-match)
          git archive --prefix=MultiOS-USB_$ver/ -o MultiOS-USB_linux_$ver.tar.gz $ver

      - name: Windows Release
        run: |
          ver=$(git describe --tags --exact-match)
          image_name="image.img"
          image_size="54542848"
          qemu-img create -f raw $image_name $image_size
          dev=$(sudo losetup -f -P --show $image_name)
          sudo ln -s ${dev}p1 ${dev}1
          sudo ln -s ${dev}p2 ${dev}2
          sed -i -e '139s/^/# /' -e '143s/^/# /' -e '152s/^/# /' -e '168s/^/# /' -e '189,190s/^/# /' installer.sh
          printf 'YeS\n' | sudo ./installer.sh $dev
          sudo losetup -d $dev
          sudo rm ${dev}1 ${dev}2
          (cd part_data && sudo zip -r ../files.zip *)
          mv docs/README_image README
          sudo zip MultiOS-USB_windows_image_$ver.zip $image_name files.zip README

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            MultiOS-USB_windows_image_*.zip
            MultiOS-USB_linux_*.tar.gz
